import os
import numpy as np
from openbabel import pybel, openbabel
from rdkit import Chem
from typing import Optional

class MemoryConversion:
    """
    Memory conversion methods collection class
    Provides all memory-to-memory molecular format conversion functions
    """
    
    @staticmethod
    def xyz_to_mol_string(xyz_str: str) -> str:
        """
        Convert XYZ format string to MOL format string (memory-to-memory)
        
        Args:
            xyz_str (str): XYZ format molecular structure string
            
        Returns:
            str: MOL format string
        """
        mol = pybel.readstring("xyz", xyz_str)
        mol_str = mol.write("mol")
        return mol_str

    @staticmethod
    def xyz_to_rdkit_mol(xyz_str: str) -> Chem.Mol:
        """
        Convert XYZ string to RDKit Mol object (completed in memory, no files needed)
        
        Args:
            xyz_str (str): XYZ format molecular structure string
            
        Returns:
            rdkit.Chem.Mol: Corresponding RDKit molecular object
        """
        # Directly use pybel to convert to MOL string, then read by RDKit
        mol = pybel.readstring("xyz", xyz_str)
        molblock = mol.write("mol")
        
        rdkit_mol = Chem.MolFromMolBlock(molblock, removeHs=False, sanitize=True)
        
        if rdkit_mol is None:
            raise ValueError("RDKit failed to parse the MOL block generated by Open Babel.")
        
        return rdkit_mol

    @staticmethod
    def xyz_to_bond_order_matrix(xyz_str: str) -> np.ndarray:
        """
        Build bond order matrix from XYZ string using Open Babel low-level API (no file I/O)
        
        Args:
            xyz_str (str): XYZ format molecular structure string
            
        Returns:
            np.ndarray: Bond order matrix with shape (n_atoms, n_atoms)
        """
        # Initialize converter and molecule object
        ob_conv = openbabel.OBConversion()
        ob_mol = openbabel.OBMol()
        
        # Set input format to "xyz"
        if not ob_conv.SetInFormat("xyz"):
            raise ValueError("XYZ format not supported")
        
        # Read from string (key! no file I/O)
        success = ob_conv.ReadString(ob_mol, xyz_str)
        if not success:
            raise ValueError("Failed to parse XYZ string")

        n_atoms = ob_mol.NumAtoms()
        bond_matrix = np.zeros((n_atoms, n_atoms), dtype=int)

        # Iterate through all bonds
        for ob_bond in openbabel.OBMolBondIter(ob_mol):
            i = ob_bond.GetBeginAtomIdx() - 1  # OB index starts from 1
            j = ob_bond.GetEndAtomIdx() - 1
            bo = ob_bond.GetBondOrder()
            bond_matrix[i, j] = bo
            bond_matrix[j, i] = bo

        return bond_matrix

    @staticmethod
    def xyz_to_inchi_string(xyz_str: str, fixed_h: bool = False) -> str:
        """
        Convert XYZ string to InChI format (memory conversion)
        
        Args:
            xyz_str (str): XYZ format molecular structure string
            fixed_h (bool): Whether to generate InChI with fixed hydrogen atoms (adds -xF flag)
            
        Returns:
            str: InChI format string
        """
        mol = pybel.readstring("xyz", xyz_str)
        ob_conv = openbabel.OBConversion()
        ob_conv.SetOutFormat("inchi")
        ob_conv.AddOption("readconformer", openbabel.OBConversion.INOPTIONS)
        
        if fixed_h:
            ob_conv.AddOption("F", openbabel.OBConversion.OUTOPTIONS)
        
        inchi_str = ob_conv.WriteString(mol.OBMol)
        return inchi_str.strip()

    @staticmethod
    def xyz_to_inchikey_string(xyz_str: str) -> str:
        """
        Convert XYZ string to InChIKey format (memory conversion)
        
        Args:
            xyz_str (str): XYZ format molecular structure string
            
        Returns:
            str: InChIKey format string
        """
        mol = pybel.readstring("xyz", xyz_str)
        inchikey_str = mol.write("inchikey")
        return inchikey_str.strip()

    @staticmethod
    def xyz_to_smiles_string(xyz_str: str) -> str:
        """
        Convert XYZ string to SMILES format (memory conversion)
        
        Args:
            xyz_str (str): XYZ format molecular structure string
            
        Returns:
            str: SMILES format string
        """
        mol = pybel.readstring("xyz", xyz_str)
        smiles_str = mol.write("smi")
        return smiles_str.split('\t')[0].strip()

    @staticmethod
    def xyz_to_sdf_string(xyz_str: str) -> str:
        """
        Convert XYZ string to SDF format string (memory conversion)
        
        Args:
            xyz_str (str): XYZ format molecular structure string
            
        Returns:
            str: SDF format string
        """
        mol = pybel.readstring("xyz", xyz_str)
        sdf_str = mol.write("sdf")
        return sdf_str
    
    @staticmethod
    def xyz_to_pdb_string(xyz_str: str) -> str:
        """
        Convert XYZ string to PDB format string (memory conversion)
        
        Args:
            xyz_str (str): XYZ format molecular structure string
            
        Returns:
            str: PDB format string
        """
        mol = pybel.readstring("xyz", xyz_str)
        pdb_str = mol.write("pdb")
        return pdb_str
    
    @staticmethod
    def xyz_to_mol2_string(xyz_str: str) -> str:
        """
        Convert XYZ string to MOL2 format string (memory conversion)
        
        Args:
            xyz_str (str): XYZ format molecular structure string
            
        Returns:
            str: MOL2 format string
        """
        mol = pybel.readstring("xyz", xyz_str)
        mol2_str = mol.write("mol2")
        return mol2_str
    
    @staticmethod
    def xyz_to_cif_string(xyz_str: str) -> str:
        """
        Convert XYZ string to CIF format string (memory conversion)
        
        Args:
            xyz_str (str): XYZ format molecular structure string
            
        Returns:
            str: CIF format string
        """
        mol = pybel.readstring("xyz", xyz_str)
        cif_str = mol.write("cif")
        return cif_str